#!/bin/bash

commit=`curl https://api.github.com/repos/google/stenographer/commits/master | awk 'NR==2{print $0}' | awk -F'"' '{print $4}'`
short_commit=`echo ${commit:0:7}`
TMP=`mktemp -d`
pushd $TMP

# pull lastest versions checked in to github
curl -L -J -O https://github.com/google/stenographer/archive/$commit.tar.gz

# create working directory for rpmbuild to use
mkdir -p $TMP/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}

# untar to pull latest specfile for use
tar -xzf stenographer-$commit.tar.gz 

# copy current spec file into the expected folder
cp $TMP/stenographer-$commit/stenographer.spec $TMP/rpmbuild/SPECS/ 

# run rpmbuild to create source rpm
rpmbuild --define "_topdir $TMP/rpmbuild" -bs $TMP/rpmbuild/SPECS/stenographer.spec

# use mock to create rpm for centos 7
sudo mock -r epel-7-x86_64 --init
sudo mock -r epel-7-x86_64 --clean
sudo mock -r epel-7-x86_64 rebuild $TMP/rpmbuild/SRPMS/stenographer-*$short_commit.el7.src.rpm



