#!/bin/bash

commit=`curl https://api.github.com/repos/google/stenographer/commits/master | awk 'NR==2{print $0}' | awk -F'"' '{print $4}'`
short_commit=`echo ${commit:0:7}`

# pull lastest versions checked in to github
curl -L -J -O https://github.com/google/stenographer/archive/$commit.tar.gz

# move and untar in expected rpmbuild directories
mv ~/stenographer-$commit.tar.gz ~/rpmbuild/SOURCES/
tar -xzf ~/rpmbuild/SOURCES/stenographer-$commit.tar.gz -C ~/rpmbuild/SOURCES/

# copy current spec file into the expected folder
cp ~/rpmbuild/SOURCES/stenographer-$commit/stenographer.spec ~/rpmbuild/SPECS/ 

# run rpmbuild to create source rpm
rpmbuild -bs ~/rpmbuild/SPECS/stenographer.spec

# use mock to create rpm for centos 7
sudo mock -r epel-7-x86_64 --init
sudo mock -r epel-7-x86_64 --clean
sudo mock -r epel-7-x86_64 rebuild ~/rpmbuild/SRPMS/stenographer-*$short_commit.el7.src.rpm



