#!/bin/bash
# Copyright 2014 Google Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

if [ "$#" -lt 1 ]; then
  cat >&2 <<EOF
$0 provides a simple method for reading logs out of stenographer.
Its first argument is the query to send to stenographer, all other arguments
are passed to TCPDump.

Examples:
 # Print all packets for source IP 1.1.1.1 without DNS resolution (-n).
 $0 'host 1.1.1.1' -n src host 1.1.1.1
 # Print all PSH packets between 1.1.1.1 and 2.2.2.2:
 $0 'host 1.1.1.1 and host 2.2.2.2' -n 'tcp[tcpflags] & tcp-push != 0'
 # Write all packets between 1.1.1.1 and 2.2.2.2 to disk.
'host 1.1.1.1 and host 2.2.2.2' -w /tmp/out.pcap

See README.md for more details on the Stenographer query language.

Set the STENOGRAPHER_CONFIG environmental variable to point to your stenographer
config if it's in a nonstandard place (defaults to /etc/stenographer/config).
EOF
  exit 1
fi

STENOQUERY="$1"
shift

TCPDUMP=$(PATH=$PATH:/usr/local/sbin:/usr/sbin:/sbin which tcpdump)
STENOCURL=$(PATH=$(dirname "$0"):$PATH which stenocurl)

echo "Running stenographer query '$STENOQUERY', piping to 'tcpdump $@'" >&2
"$STENOCURL" /query \
    -d "$STENOQUERY" \
    --silent \
    --max-time 890 \
    --show-error |
    "$TCPDUMP" -r /dev/stdin -s 0 "$@"
